export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Solutions", href: "/solutions" },
  { label: "EcoTrike", href: "/ecotrike" },
  { label: "Market Edge", href: "/market-analysis" },
  { label: "Leadership", href: "/team" },
  { label: "News & Updates", href: "/gallery" },
  { label: "Contact", href: "/contact" },
];

export const STATS = [
  { value: 625, unit: "kWh", label: "Battery Capacity" },
  { value: 205, unit: "+", label: "Solar Panels" },
  { value: 125, unit: "EV", label: "Daily" },
  { value: 5, unit: "+", label: "Plants" },
];

export const SOLUTIONS = [
  {
    id: "ev-charging",
    tag: "EV Charging",
    title: "EV Charging Infrastructure",
    description:
      "Solar + grid hybrid powered battery swap stations with smart IoT analytics, rapid-swap interface, and scalable station formats   built for electric three-wheelers and vehicles across Bangladesh.",
    img: "/assets/images/charging-station.png",
    alt: "Xeltra solar-powered EV battery swap and charging station",
    specs: [
      { label: "Battery", value: "48V 100Ah Smart BMS & GPS" },
      { label: "Solar Panels", value: "585W Per Panel" },
      { label: "Charger", value: "MPPT Controller & Invertor" },
      { label: "Station Formats", value: "12 / 24 / 50 Battery" },
    ],
    ecosystem: [
      "Solar + grid hybrid energy input",
      "Smart battery racks",
      "Rapid swap interface",
      "Operator dashboard & IoT analytics",
    ],
    stationFormats: [
      { size: "12", label: "Battery Station" },
      { size: "24", label: "Battery Station" },
      { size: "50", label: "Battery Station" },
    ],
    productDetails: [
      "48V100Ah Battery with Smart BMS & GPS",
      "MPPT Charger Controller & Invertor",
      "585W Solar Panels & Battery Station",
    ],
    icon: "⚡",
  },
  {
    id: "solar",
    tag: "Solar Energy",
    title: "Home Solar Solutions",
    description:
      "Professional solar installation with ESS backup for homes, businesses, and facilities. Reduce your electricity bill by up to 70–90%.",
    img: "/assets/images/solar-home.png",
    alt: "Xeltra home solar installation with 5kW ESS battery backup",
    specs: [
      { label: "System Size", value: "5kW ESS" },
      { label: "Bill Reduction", value: "70–90%" },
      { label: "Power Supply", value: "24/7" },
      { label: "Investment", value: "Long-term ROI" },
    ],
    icon: "☀️",
  },
  {
    id: "power-bank",
    tag: "Energy Bank",
    title: "Be a Proud Owner of Solar Plant",
    description:
      "Invest in an income-generating asset positioned at the intersection of three powerful market shifts: rising energy costs, growing demand for reliable electricity, and Bangladesh’s transition toward cleaner energy.",
    img: "/assets/images/power-bank.png",
    alt: "Xeltra Energy Bank & Solar Plant Investment",
    specs: [
      { label: "Daily Production", value: "625 kW" },
      { label: "Customers", value: "100+ Daily" },
      { label: "Est. ROI", value: "~4.6 Years" },
      { label: "Deployment", value: "Scalable Fleet" },
    ],
    icon: "🔋",
  },
];

export const CONTRIBUTIONS = [
  { city: "CMB Chittagong", type: "Solar Installation", id: "ctg" },
  { city: "Cumilla BSIC", type: "Solar Installation", id: "cumilla" },
  { city: "Khulshi, CTG", type: "Solar Installation", id: "khulshi" },
  { city: "Chanpur, Cumilla", type: "Solar Installation", id: "chanpur" },
];

export const ECOTRIKE_SPECS = [
  { icon: "⚙️", value: "1200W", label: "BLDC Motor" },
  { icon: "🛣️", value: "80–100 km", label: "Range/Charge" },
  { icon: "🔋", value: "48V 100–150Ah", label: "Li-ion Battery" },
  { icon: "⚖️", value: "320 kg", label: "Max Load" },
  { icon: "⏱️", value: "4–6 Hours", label: "Charging Time" },
  { icon: "🚀", value: "35 km/h", label: "Max Speed (loaded)" },
  { icon: "📐", value: "12%", label: "Gradeability" },
  { icon: "🔩", value: "2.5 mm Steel", label: "Tubular Chassis" },
];

export const ECOTRIKE_FEATURES = [
  "100% Electric   Zero Emissions",
  "Driver + 2 Passengers",
  "Rear Wheel Drive",
  "Smart BMS with Heat Sensor",
  "Telescopic Hydraulic Front Fork",
  "Rear Leaf Spring / Hydraulic Shock Absorbers",
  "Front Disc Brake",
  "Rear Drum Brake",
  "3.00–18 Steel Spoke Wheels",
  "Weather-Resistant Canopy",
  "Reinforced Fiberglass Body",
  "LED Headlamp & Indicators",
  "Digital Speedometer",
  "Solar-Powered Charging Compatible",
];

export const ECOTRIKE_HIGHLIGHTS = [
  {
    icon: "🏛️",
    title: "Heritage Modernism",
    desc: "Inspired by the heritage pedal rickshaw of Bangladesh, EcoTrike EVX1 preserves the familiar cultural form while replacing conventional propulsion with modern electric mobility. We electrify the heritage design to help keep the character of Bangladesh's rickshaw tradition alive.",
  },
  {
    icon: "☀️",
    title: "Solar-Powered Charging",
    desc: "Charged through Xeltra Energy's Solar-Powered Charging Station. Clean-energy charging infrastructure designed to support EcoTrike electric mobility.",
  },
];

export const TEAM = [
  {
    id: "golam",
    name: "Golam Qadir Chowdhury",
    role: "Chairman",
    img: "/assets/team/golam.jpeg",
    bio: "Leading Xeltra Energy with strategic vision, corporate governance, and long-term institutional direction.",
    featured: true,
    imgClass: "object-cover object-top",
  },
  {
    id: "chairman",
    name: "Zaheda Akhter Mita",
    role: "Vice Chairman",
    img: "/assets/team/chairman.jpeg",
    bio: "Guiding governance, corporate ethics, and long-term sustainability strategy.",
    featured: true,
    imgClass: "object-cover object-top",
  },
  {
    id: "sajid",
    name: "Moktadir Sajid",
    role: "Founder & Managing Director",
    img: "/assets/team/sajid.png",
    bio: "Pioneering Xeltra Energy's technology vision and renewable infrastructure deployment.",
    featured: true,
    imgClass: "object-contain p-1",
  },
  {
    id: "ceo",
    name: "Subarna Dey",
    role: "CEO",
    img: "/assets/team/ceo.png",
    bio: "Spearheading business expansion, strategic partnerships, and operations across Bangladesh.",
    featured: false,
    imgClass: "object-contain p-1",
  },
  {
    id: "shamim",
    name: "Shamim Mohammad Osman",
    role: "Engineering & Project Director",
    img: "/assets/team/shamim.png",
    bio: "Heading hardware engineering, solar installations, and station maintenance.",
    featured: false,
    imgClass: "object-contain p-1",
  },
  {
    id: "sharfuddin",
    name: "Mohammad Sharfuddin",
    role: "Chief Operating Officer & Director",
    img: "/assets/team/sharfuddin.jpeg",
    bio: "Overseeing operations, battery research, telemetry testing, and product refinement.",
    featured: false,
    imgClass: "object-cover object-top",
  },
  {
    id: "lutfur",
    name: "Luthfur Rahman",
    role: "Public Relations Director",
    img: "/assets/team/lutfur.jpeg",
    bio: "Leading government liaisons, public affairs, and institutional communications.",
    featured: false,
    imgClass: "object-cover object-top",
  },
  {
    id: "gias",
    name: "Mohammad Gias",
    role: "Chief Financial Officer & Director",
    img: "/assets/team/gias.png",
    bio: "Managing financial strategy, capital investments, and fiscal growth.",
    featured: false,
    imgClass: "object-contain p-1",
  },
  {
    id: "rizwana",
    name: "Rizwana Hossain Chowdhury",
    role: "Director & Financial Executive",
    img: "/assets/team/rizwana.png",
    bio: "Handling financial accounting, budgeting, and corporate audit operations.",
    featured: false,
    imgClass: "object-contain p-1",
  },
  {
    id: "riduan",
    name: "Md. Riduanul Haque",
    role: "Chief Technology Officer (CTO)",
    img: "/assets/team/riduan.png",
    bio: "Directing software architecture, IoT telemetry, web applications, and smart battery management systems.",
    featured: false,
    imgClass: "object-contain p-1 bg-slate-900",
  },
  {
    id: "duniya",
    name: "Duniya Khandoker",
    role: "Strategic Advisor – Investment & Partnerships",
    img: "/assets/team/duniya.png",
    bio: "Advising on institutional partnerships, global investor relations, and capital expansion.",
    featured: false,
    imgClass: "object-contain p-1",
  },
  {
    id: "wasif",
    name: "Wasif Zamal Jishan",
    role: "Marketing Executive",
    img: "/assets/team/wasif.png",
    bio: "Managing digital outreach, promotional campaigns, and brand communications.",
    featured: false,
    imgClass: "object-contain p-1",
  },
];

export const ACHIEVEMENTS = [
  {
    icon: "📋",
    title: "SREDA License",
    desc: "EV Charging Station license applied from SREDA (Sustainable and Renewable Energy Development Authority)",
    id: "sreda",
  },
  {
    icon: "🏆",
    title: "Trade Fair Participation",
    desc: "Participated in national and international trade fairs showcasing Xeltra's clean energy ecosystem",
    id: "tradefair",
  },
  {
    icon: "🤝",
    title: "Global Partners",
    desc: "Strategic partnerships with HYSTORIX, LV TOPSUN, TIAN LU, GWTIME & China Cable Corporation",
    id: "partners",
  },
  {
    icon: "☀️",
    title: "4+ Solar Sites",
    desc: "Completed rooftop solar installations across Chittagong, Cumilla, Khulshi, and Chanpur",
    id: "solar-sites",
  },
];

export const PARTNERS = [
  { id: "xentro", name: "Xentro", logo: "/assets/logo/Xentro.png", tag: "Technology Partner", icon: "🔌", country: "Bangladesh", flag: "🇧🇩" },
  { id: "ecotrike", name: "EcoTrike", logo: "/assets/logo/ecotrike-logo.png", tag: "Electric Vehicle Brand", icon: "⚡", country: "Bangladesh", flag: "🇧🇩" },
];

export const GLOBAL_PARTNERS = [
  { name: "HYSTORIX", country: "China", id: "hystorix" },
  { name: "LV TOPSUN", country: "China", id: "lvtopsun" },
  { name: "TIAN LU", country: "China", id: "tianlu" },
  { name: "GWTIME", country: "China", id: "gwtime" },
  { name: "China Cable Corp.", country: "China", id: "chinacable" },
];

export const GALLERY_IMAGES = [
  {
    src: "/assets/images/solar-panel-microgrid.png",
    alt: "High-tech rooftop solar panel array and solar-powered EV charging station in Bangladesh",
    caption: "High-Capacity Rooftop Solar Array & Charging Depot",
    category: "Solar Installations",
    wide: true,
    id: "gallery-solar-microgrid",
  },
  {
    src: "/assets/images/whatsapp7.jpg",
    alt: "Rooftop solar panel installation by Xeltra Energy engineers",
    caption: "Commercial Rooftop Solar Array Installation",
    category: "Solar Installations",
    wide: false,
    id: "gallery-wa7",
  },
  {
    src: "/assets/images/whatsapp2.jpg",
    alt: "Aerial view of Xeltra Energy solar powered hub with rickshaw charging",
    caption: "Xeltra Solar-Powered Charging Hub   Aerial View",
    category: "Solar Installations",
    wide: true,
    id: "gallery-wa2",
  },
  {
    src: "/assets/images/whatsapp13.jpg",
    alt: "Off-grid solar panel array mounting on commercial roof",
    caption: "Off-Grid Photovoltaic Panel Array Setup",
    category: "Solar Installations",
    wide: false,
    id: "gallery-wa13",
  },
  {
    src: "/assets/images/whatsapp1.jpg",
    alt: "Xeltra engineers demonstrating MPPT solar controller and lithium battery",
    caption: "MPPT Solar Controller & Battery System Demo",
    category: "Field Operations",
    wide: false,
    id: "gallery-wa1",
  },
  {
    src: "/assets/images/whatsapp12.jpg",
    alt: "Electric three-wheeler EV charging at Xeltra station",
    caption: "EcoTrike EV Swapping & Charging Depot",
    category: "Battery Swapping",
    wide: false,
    id: "gallery-wa12",
  },
  {
    src: "/assets/images/whatsapp10.jpg",
    alt: "Xeltra Energy team at battery swap station showcase",
    caption: "Xeltra Energy Operations & Engineering Team",
    category: "Team & Events",
    wide: true,
    id: "gallery-wa10",
  },
  {
    src: "/assets/images/whatsapp5.jpg",
    alt: "Xeltra Energy leadership with international partners banner",
    caption: "Xeltra Leadership & Global Strategic Partners",
    category: "Team & Events",
    wide: false,
    id: "gallery-wa5",
  },
  {
    src: "/assets/images/whatsapp6.jpg",
    alt: "Solar panel mounting and structural alignment on roof",
    caption: "High-Durability Solar Panel Roof Mounting",
    category: "Solar Installations",
    wide: false,
    id: "gallery-wa6",
  },
  {
    src: "/assets/images/whatsapp8.jpg",
    alt: "MPPT Solar Charge Controller and Smart BMS Setup",
    caption: "Solar MPPT Inverter & Lithium Storage Unit",
    category: "Field Operations",
    wide: false,
    id: "gallery-wa8",
  },
  {
    src: "/assets/images/whatsapp9.jpg",
    alt: "Smart Lithium battery bench testing and safety checks",
    caption: "Smart BMS Thermal & Voltage Bench Testing",
    category: "Field Operations",
    wide: false,
    id: "gallery-wa9",
  },
  {
    src: "/assets/images/whatsapp11.jpg",
    alt: "On-site electrical wiring and solar commissioning work",
    caption: "On-Site Solar Commissioning & Wiring",
    category: "Field Operations",
    wide: false,
    id: "gallery-wa11",
  },
  {
    src: "/assets/images/whatsapp3.jpeg",
    alt: "Field operations team at Xeltra solar charging hub",
    caption: "Field Hub Operational Inspection",
    category: "Team & Events",
    wide: false,
    id: "gallery-wa3",
  },
  {
    src: "/assets/images/whatsapp4.jpeg",
    alt: "Battery swapping lockers and power distribution unit testing",
    caption: "Smart Battery Locker Hardware Testing",
    category: "Battery Swapping",
    wide: false,
    id: "gallery-wa4",
  },
  {
    src: "/assets/images/banner.png",
    alt: "Xeltra Energy   Battery swap station and electric rickshaw Bangladesh",
    caption: "Battery Swap Station   Powering Bangladesh's Three-Wheelers",
    category: "Battery Swapping",
    wide: true,
    id: "gallery-banner",
  },
  {
    src: "/assets/images/charging-station.png",
    alt: "Xeltra solar-powered charging station with battery lockers",
    caption: "Solar-Powered Charging Station Locker Setup",
    category: "Battery Swapping",
    wide: false,
    id: "gallery-charging",
  },
  {
    src: "/assets/images/power-bank.png",
    alt: "Xeltra Power Bank fleet at solar charging depot",
    caption: "Xeltra Mobile Power Bank Fleet",
    category: "Field Operations",
    wide: false,
    id: "gallery-powerbank",
  },
  {
    src: "/assets/images/ecotrike-heritage.png",
    alt: "Ecotrike EVX1 heritage rickshaw electrified",
    caption: "EcoTrike EVX1   Heritage Modernism Edition",
    category: "Field Operations",
    wide: false,
    id: "gallery-ecotrike",
  },
];
